name: Compare Storage Layouts
description: Compares storage layouts between branches

inputs:
  token:
    description: GitHub token
    required: true
  buildinfo:
    description: Compilation artifacts
    required: false
    default: artifacts/build-info/*.json
  layout:
    description: Extracted storage layout
    required: false
    default: HEAD.layout.json
  out_layout:
    description: Storage layout to upload
    required: false
    default: ${{ github.ref_name }}.layout.json
  ref_layout:
    description: Reference branch storage layout
    required: false
    default: ${{ github.base_ref }}.layout.json

runs:
  using: composite
  steps:
    - name: Extract Storage Layout
      run: node scripts/checks/extract-layout.js ${{ inputs.buildinfo }} > ${{ inputs.layout }}
      shell: bash

    - name: Download Reference Layout
      if: github.event_name == 'pull_request'
      env:
        GITHUB_TOKEN: ${{ inputs.token }}
      run: |
        RUN_ID=$(gh run list --repo ${{ github.repository }} --branch ${{ github.base_ref }} \
                 --workflow ${{ github.workflow }} --limit 100 \
                 --json 'conclusion,databaseId,event' \
                 --jq 'map(select(.conclusion=="success" and .event!="pull_request"))[0].databaseId')
        [ -n "$RUN_ID" ] && gh run download "$RUN_ID" --repo ${{ github.repository }} -n layout || echo "No reference layout found."
      shell: bash
      continue-on-error: true
      id: reference_download

    - name: Compare Storage Layouts
      if: steps.reference_download.outcome == 'success' && github.event_name == 'pull_request'
      run: node scripts/checks/compare-layout.js --head ${{ inputs.layout }} --ref ${{ inputs.ref_layout }}
      shell: bash

    - name: Prepare Artifacts for Upload
      if: github.event_name != 'pull_request'
      run: mv ${{ inputs.layout }} ${{ inputs.out_layout }}
      shell: bash

    - name: Upload Storage Layout Artifact
      if: github.event_name != 'pull_request'
      uses: actions/upload-artifact@v4
      with:
        name: layout
        overwrite: true
        path: ${{ inputs.out_layout }}
